-- ═══════════════════════════════════════════════════════════
-- Order Hub — Supabase schema
-- Run this whole file once in: Supabase Dashboard → SQL Editor
-- ═══════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

-- ── Order lists (was the Order_List master sheet) ────────────
create table if not exists public.order_lists (
  id          uuid primary key default gen_random_uuid(),
  seq         bigint generated by default as identity,
  name        text not null default '',
  description text not null default '',
  image       text not null default '',
  status      text not null default 'Open',   -- Open | Closed
  display     text not null default 'Show',   -- Show | Hidden
  created_at  timestamptz not null default now()
);

-- ── Products (was the Products sheet in each shop spreadsheet) ─
create table if not exists public.products (
  id         uuid primary key default gen_random_uuid(),
  seq        bigint generated by default as identity,
  list_id    uuid not null references public.order_lists(id) on delete cascade,
  code       text not null default '',        -- product ID / barcode (old col A)
  name       text not null default '',
  image      text not null default '',
  price      numeric not null default 0,
  deposit    numeric not null default 0,
  remaining  numeric,                          -- NULL = unlimited stock
  status     text not null default 'Open',
  yuan       numeric not null default 0,
  options    text not null default '',         -- "Name:barcode,Name:barcode"
  created_at timestamptz not null default now()
);
create index if not exists products_list_idx on public.products(list_id);

-- ── Orders (was the Orders sheet) ────────────────────────────
create table if not exists public.orders (
  id         uuid primary key default gen_random_uuid(),
  seq        bigint generated by default as identity,
  list_id    uuid not null references public.order_lists(id) on delete cascade,
  customer   text not null default '',
  product    text not null default '',
  qty        numeric not null default 0,
  pay_type   text not null default 'Full Price',   -- Deposit | Full Price
  price      numeric not null default 0,
  total      numeric not null default 0,
  yuan       numeric not null default 0,
  total_yuan numeric not null default 0,
  full_price numeric not null default 0,
  total_full numeric not null default 0,
  remark     text not null default '',             -- customer phone
  created_at timestamptz not null default now()
);
create index if not exists orders_list_idx on public.orders(list_id);

-- ── Stock / warehouse (was the "Stock" sheet in Shop_Util) ───
-- parent_id NULL = parent product (level 0); set = option row (level 1)
create table if not exists public.stock_items (
  id         uuid primary key default gen_random_uuid(),
  seq        bigint generated by default as identity,
  parent_id  uuid references public.stock_items(id) on delete cascade,
  code       text not null default '',
  name       text not null default '',
  image      text not null default '',
  price      numeric not null default 0,
  deposit    numeric not null default 0,
  yuan       numeric not null default 0,
  stock      numeric,                         -- NULL = unlimited
  status     text not null default 'Open',
  created_at timestamptz not null default now()
);

-- ── Restock-notify recipient list (was the Whitelist sheet) ──
create table if not exists public.notify_emails (
  email text primary key
);
insert into public.notify_emails(email) values
  ('ongkub001@gmail.com'),
  ('pyatadaja@gmail.com')
on conflict do nothing;

-- ═══════════════════════════════════════════════════════════
-- Row Level Security
--  * shop front (anon):  read lists + products, submit orders via RPC
--  * admin (Supabase Auth user): full access
-- ═══════════════════════════════════════════════════════════
alter table public.order_lists  enable row level security;
alter table public.products     enable row level security;
alter table public.orders       enable row level security;
alter table public.stock_items  enable row level security;
alter table public.notify_emails enable row level security;

-- order_lists
drop policy if exists lists_public_read  on public.order_lists;
drop policy if exists lists_admin_write  on public.order_lists;
create policy lists_public_read on public.order_lists
  for select using (true);
create policy lists_admin_write on public.order_lists
  for all to authenticated using (true) with check (true);

-- products
drop policy if exists products_public_read on public.products;
drop policy if exists products_admin_write on public.products;
create policy products_public_read on public.products
  for select using (true);
create policy products_admin_write on public.products
  for all to authenticated using (true) with check (true);

-- orders (public inserts happen through the submit_order RPC below)
drop policy if exists orders_admin_all on public.orders;
create policy orders_admin_all on public.orders
  for all to authenticated using (true) with check (true);

-- stock (admin only)
drop policy if exists stock_admin_all on public.stock_items;
create policy stock_admin_all on public.stock_items
  for all to authenticated using (true) with check (true);

-- notify emails (admin read)
drop policy if exists notify_admin_read on public.notify_emails;
create policy notify_admin_read on public.notify_emails
  for select to authenticated using (true);

-- ═══════════════════════════════════════════════════════════
-- submit_order — atomic order submission for the public shop
-- (replaces LockService + stock deduction in code.gs)
-- items: [{ id, quantity, isDeposit, selectedOption }]
-- ═══════════════════════════════════════════════════════════
create or replace function public.submit_order(
  p_list_id  uuid,
  p_customer text,
  p_phone    text,
  p_items    jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  it       jsonb;
  prod     public.products%rowtype;
  v_qty    numeric;
  v_is_dep boolean;
  v_opt    text;
  v_unit   numeric;
  v_label  text;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    return jsonb_build_object('status', 'Error', 'message', 'No order items received');
  end if;

  -- 1) validate stock (and lock the rows)
  for it in select * from jsonb_array_elements(p_items) loop
    select * into prod from public.products
      where list_id = p_list_id and code = (it->>'id')
      order by seq limit 1
      for update;
    if not found then
      return jsonb_build_object('status', 'Error', 'message', 'Product not found: ' || coalesce(it->>'id', ''));
    end if;
    v_qty := coalesce((it->>'quantity')::numeric, 1);
    if prod.remaining is not null and prod.remaining < v_qty then
      return jsonb_build_object('status', 'Error', 'message', 'Stock not enough for ' || prod.name);
    end if;
  end loop;

  -- 2) deduct stock + insert order rows
  for it in select * from jsonb_array_elements(p_items) loop
    select * into prod from public.products
      where list_id = p_list_id and code = (it->>'id')
      order by seq limit 1
      for update;

    v_qty    := coalesce((it->>'quantity')::numeric, 1);
    v_is_dep := coalesce((it->>'isDeposit')::boolean, false);
    v_opt    := coalesce(it->>'selectedOption', '');

    if prod.remaining is not null then
      update public.products set remaining = remaining - v_qty where id = prod.id;
    end if;

    v_unit  := case when v_is_dep then coalesce(prod.deposit, 0) else coalesce(prod.price, 0) end;
    v_label := case when v_opt <> '' then prod.name || ' (' || v_opt || ')' else prod.name end;

    insert into public.orders
      (list_id, customer, product, qty, pay_type, price, total,
       yuan, total_yuan, full_price, total_full, remark)
    values
      (p_list_id, coalesce(p_customer, ''), v_label, v_qty,
       case when v_is_dep then 'Deposit' else 'Full Price' end,
       v_unit, v_unit * v_qty,
       coalesce(prod.yuan, 0), coalesce(prod.yuan, 0) * v_qty,
       coalesce(prod.price, 0), coalesce(prod.price, 0) * v_qty,
       coalesce(p_phone, ''));
  end loop;

  return jsonb_build_object('status', 'Success');
end;
$$;

revoke all on function public.submit_order(uuid, text, text, jsonb) from public;
grant execute on function public.submit_order(uuid, text, text, jsonb) to anon, authenticated;
